spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdg
    username: ${LOCAL_DB_NAME}
    password: ${LOCAL_DB_PW}
    # 배포용
#    url: jdbc:mysql://gdgdb.cpoeeaowebbq.ap-northeast-2.rds.amazonaws.com:3306/gdg_db
#    username: root
#    password: sokcho007!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update #create, update
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: gdg-booket
      path:
        file: books
#        review: review
        book: book
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

#jwt:
#  secret: ${JWT_SECRET_KEY}
#  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
#  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}
#lt_batch_fetch_size: 1000
